apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vuubofzdx-nodejs
  janus-idp.io/tekton: vuubofzdx-nodejs
  backstage.io/kubernetes-id: vuubofzdx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vuubofzdx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
